name: Main Branch CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  main:
    name: Main Branch CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Compile
        run: mvn -B clean compile -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify
        run: mvn -B verify

      - name: Get Latest Tag
        id: get-latest-tag
        uses: actions-ecosystem/action-get-latest-tag@v1
        with:
          semver_only: true

      # currently hardcoding the semver increment to patch
      # there are a handful of ways to determine this, PR labels, commit message parsing or just keep it always manual
      - name: Bump Version
        id: bump-semver
        uses: actions-ecosystem/action-bump-semver@v1
        if: ${{ steps.get-latest-tag.outputs.tag != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch

      - name: Docker Build & Push
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          IMAGE_VERSION=$(echo ${{ steps.bump-semver.outputs.new_version }} | cut -c 2-)
          IMAGE_NAME=$(echo ghcr.io/${{ github.repository }}:${IMAGE_VERSION} | awk '{print tolower($0)}')
          echo ${IMAGE_NAME}
          mvn -B spring-boot:build-image -DskipTests -Drevision=${IMAGE_VERSION} -Dspring-boot.build-image.imageName=${IMAGE_NAME}
          docker push ${IMAGE_NAME}

      - name: Tag & Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump-semver.outputs.new_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

