name: Main Branch CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  main:
    name: Main Branch CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag
        with:
          semver_only: true

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Compile
        run: mvn -B clean compile -DskipTests

      - name: Verify
        run: mvn -B clean verify

      # currently hardcoding the semver increment to patch
      # there are a handful of ways to determine this, PR labels, commit message parsing or just keep it always manual
      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ steps.get-latest-tag.outputs.tag != null }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}
          level: patch

      - name: Publish Main Artifacts
        run: mvn -B deploy -Drevision=${{ steps.bump-semver.outputs.new_version }} -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag & Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.bump-semver.outputs.new_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

